version: '3.8'
services:
  mongo:
    image: mongo
    container_name: bot-mongo-container
    restart: always
    ports:
        - "27020:27017"
    networks:
      - bot
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: bot_db
    volumes:
      - ./mongodb-data:/data/db
      - ./mongodb-log:/var/log/mongodb
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    command:
      - '--logpath'
      - '/var/log/mongodb/mongodb.log'

  mongo-express:
    image: mongo-express
    container_name: bot-mongo-express-container
    restart: always
    depends_on:
      - mongo
    ports:
      - "8090:8081"
    networks:
      - bot
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@bot-mongo-container:27017/

networks:
  bot:
    driver: bridge
